### ISSUE TITLE
Removing loopback on /etc/hosts of each guest host goes too far.

### ISSUE THREAD

**Issue by romulogoncalves** [nlesc-sherlock/emma#15]
Inline with:
https://github.com/nlesc-sherlock/emma/issues/14

The loopback clean done by  roles/common/tasks/main.yml removes the external IP entry for the local host. The reg-exp should only remove the loopback for 127.0.0.1.

**Comment by romulogoncalves** [comment]
At the moment the loopback removal does not happen.
https://github.com/nlesc-sherlock/emma/commit/8fd773fa53893eeabeaa84d25fcecb2f121eaa3f

Waiting for the regexp to be improved.

**Comment by sverhoeven** [comment]
And remove hostname for 127.0.1.1

**Comment by romulogoncalves** [comment]
Solved by 
https://github.com/nlesc-sherlock/emma/commit/750aa7018d86acb6fbcf27b2b1db37e7501cb766
