### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by sverhoeven** [nlesc-sherlock/emma#2]
Demos

* [ ] romulo
  * [x] dns
  * [ ] homepage
  * [x] swarm status
  * [x] spark UI
  * [x] JupyterHub
* [ ] carlos
  * [x] git clone
  * [x] pip inst req.txt all nodes
  * [ ] wget result
  * [ ] spot result
  * [ ] cwl run example
* [ ] janneke
  * [x] git clone
  * [x] pip inst req.txt all nodes
  * [x] cp notebooks ~emma/
  * [ ] wget output
  * [ ] spot result
  * [ ] cwl run example
* [ ] berend
  * [ ] wget input
  * [ ] wget output
  * [ ] docker demosite
* [ ]  jurriaan
  * [ ] docker spiral punch metro
* [ ] ben
  * [x] git clone
  * [x] pip inst req.txt all nodes
  * [x] cp notebooks ~emma/
  * [ ] wget input or in repo
  * [ ] wget output or in repo
  * [ ] cwl run
  * [ ] docker dive embed

**Comment by romulogoncalves** [comment]
Sherlock specific.
