### ISSUE TITLE
Use default values in vars/*.template

### ISSUE THREAD

**Issue by sverhoeven** [nlesc-sherlock/emma#43]
In `vars/common_vars.yml.template` the java_home must be set, while there is a default, please change all `vars/*template` files so the default value is already used as value, similar as done in `hadoop_vars.yml.template`.
This will make the prep work less.

**Comment by romulogoncalves** [comment]
Ok I will do that, however, in common_vars there default path is given by example.
For the minio the access key and the secret key should not be set, right?

Changes added by:
https://github.com/nlesc-sherlock/emma/pull/40/commits/b2d8255d931b173713bf03cb9d8348c5a78ddbc7

**Comment by sverhoeven** [comment]
Correct secrets should not have a default.
