### ISSUE TITLE
Improve general documentation

### ISSUE THREAD

**Issue by lbogaardt** [nlesc-sherlock/emma#70]
- [x] 1. Line `git clone https://github.com/nlesc-sherlock/emma` > For Windows users, make sure to checkout UNIX style
- [x] 2. Line `export PATH=$PATH:/mnt/c/Windows/System32/` > Add more explanation: when will this be needed
- [x] 3. Line `vim env_linux.sh` > Add more explanation: what needs to be edited
- [x] 4. Line `ssh-keygen -f ${HOST_NAME}.key` > Add that `${HOST_NAME}` may need to be manually filled
- [x] 5. Note that, all `.sh` files should be checked out in UNIX format (`\n`) instead of Windows (`\r\n`).
- [x] 6. Line `ssh-keygen -f ${HOST_NAME}.key` > specifically mention not to use a passphrase
- [x] 7. Line `The roles defined for Ansible will create a platform with the following features:` > Tell the user to go inside each sub-ReadMe and follow the steps.
- [ ] 8. Change to hadoop_prev_version: "2.8.1" > version 2.8.0 was removed from the archive

**Comment by lbogaardt** [comment]
Also, I think the path to Vagrant_Home should be set in 'Ubuntu style': /mnt/c/Ha../Va../home

**Comment by romulogoncalves** [comment]
Solved by:

fb9f81a6ec2673247c4b588bf00d196e37ef9d93
57528ec00497d45558e9118365bfc96dfd27d3fe
b2aa0d2ccdda23fb3e13c7dd1e26403cd4ef25f0
fb9f81a6ec2673247c4b588bf00d196e37ef9d93

**Comment by romulogoncalves** [comment]
Changes were merger into the master by:
https://github.com/nlesc-sherlock/emma/pull/73
