### ISSUE TITLE
Improve Ansible Documentation

### ISSUE THREAD

**Issue by lbogaardt** [nlesc-sherlock/emma#72]
- [x] 1. Line `pip install ansible` > `sudo apt-get install ansible`
- [x] 2. Look at https://github.com/ansible/ansible/issues/22998 > "hostfile was deprecated in 2.0 and removed in 2.4, use 'inventory' instead"
- [x] 3. Look at http://docs.ansible.com/ansible/latest/intro_installation.html#latest-releases-via-apt-ubuntu to get latest version
- [x] 4. HostName and UserName is assumed to be the same when using the ssh key

**Comment by romulogoncalves** [comment]
All solved by:
7ff97059a17a3d40a4cf289424f37b748df4a121

**Comment by romulogoncalves** [comment]
Changes were merger into the master by:
https://github.com/nlesc-sherlock/emma/pull/73
